import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "My Todo App",
    description: "A simple todo application built with Next.js",
    url: "https://nextjs-todo-app-451d.vercel.app/", // あなたのアプリケーションのURLに置き換えてください
    siteName: "My Todo App",
    images: [
      {
        url: "https://i.gyazo.com/587423e0dfa9cd6721a5a958e890d685.png", // OGP画像のURLに置き換えてください
        width: 1200,
        height: 630,
        alt: "My Todo App OGP Image",
      },
    ],
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
